### PR TITLE
[closes #23] Add support for class level annotations

### LINKED ISSUE #23: Add support for Jira annotation on the class level.
It would be great to use Jira annotation on whole class because when I have tests for some component and this component does not work at all I have to add Jira annotation to every test method. It is very annoying.

### PR DESCRIPTION
**Pull request by basovnik**
- `@Jira`
- `@GitHub`
- `@Redmine`

### CODE REVIEW

**Comment by smiklosovic** [comment]
Nice one! Thanks. I like that logic. One thing is that hiw to handle the situation when jira issue is supposed to be closed when test method has passed but another has failed? What we would really want is to close that issue only on case all test methods with that issue has passed.

**Comment by basovnik** [comment]
The new behaviour is the same as the old one. We can imagine that class annotation is just copied to every method where it is not already. Your request will change the behaviour a little bit. I suppose that two annotations with the same ID in different test classes will be ignored for advanced issue closing. So advanced issue closing will be in test class scope only. My question is should I create new issue for this request or include it to the current pull request?

**Comment by smiklosovic** [comment]
I woul include it in this but as a separate commit on top of this, just dont squash it.

I think that it would just need to be moved to application scope instead of class scope and you would be able to do the same.

**Comment by basovnik** [comment]
What do you think about the last commit? 83ca5f2df74941ae717d3e703d7204923b15e12c

File: api/src/main/java/org/arquillian/extension/governor/api/ClosePassedDecider.java [hunk 1]
```diff
@@ -0,0 +1,35 @@
...
+import java.lang.annotation.Annotation;
+import java.lang.reflect.Method;
+import java.util.List;
+import java.util.Map;
+
+/**
+ * @author <a href="mailto:mbasovni@redhat.com">Martin Basovnik</a>
+ *
+ */
+public interface ClosePassedDecider
```
Comment (smiklosovic) [inline api/src/main/java/org/arquillian/extension/governor/api/ClosePassedDecider.java]: please add javadoc all over the place

File: impl/src/main/java/org/arquillian/extension/governor/impl/ClosePassedDeciderImpl.java [hunk 2]
```diff
@@ -0,0 +1,75 @@
...
+
+    @Override
+    public void setClosable(Annotation annotation, boolean closeable) {
+        for (Map.Entry<Annotation, Boolean> entry : closableAnnotationMap.entrySet()) {
+            Annotation oldAnnotation = entry.getKey();
+            if (oldAnnotation.annotationType().equals(annotation.annotationType())) {
+                String oldId = getAnnotationValue(oldAnnotation);
+                String id = getAnnotationValue(annotation);
+                if (oldId != null && oldId.equals(id)) {
+                    closableAnnotationMap.put(oldAnnotation, entry.getValue().booleanValue() & closeable);
```
Comment (smiklosovic) [inline impl/src/main/java/org/arquillian/extension/governor/impl/ClosePassedDeciderImpl.java]: this basically means that when I have two e.g. jiras with the same jira id but they have diffrent close booleans, it will not be closed eventually when at least one of them is set to false?

File: impl/src/main/java/org/arquillian/extension/governor/impl/GovernorTestClassScanner.java [hunk 3]
```diff
@@ -61,6 +67,12 @@
     @Inject
     private Instance<GovernorConfiguration> governorConfiguration;
 
+    public void onBeforeSuite(@Observes BeforeSuite event) {
+        if (closePassedDecider.get() == null) {
```
Comment (smiklosovic) [inline impl/src/main/java/org/arquillian/extension/governor/impl/GovernorTestClassScanner.java]: what if close passed decider is not null here? it means that it will be used in another "suite" cycle? what  about setting this to new impl every time? something like closePassedDecider.get() = null; closePassedDecider.set(new impl);

File: impl/src/main/java/org/arquillian/extension/governor/impl/GovernorTestClassScanner.java [hunk 4]
```diff
@@ -145,4 +178,18 @@ private void checkGovernorProviderUniqueness(final Collection<GovernorProvider>
 
         return methodAnnotationsMap;
     }
+
+    private boolean isTestMethod(Method method) {
+        List<String> supportedTestAnnotations = new ArrayList<String>();
+        supportedTestAnnotations.add("org.junit.Test"); // JUnit
```
Comment (smiklosovic) [inline impl/src/main/java/org/arquillian/extension/governor/impl/GovernorTestClassScanner.java]: :+1:

Comment (smiklosovic) [inline impl/src/main/java/org/arquillian/extension/governor/impl/GovernorTestClassScanner.java]: I would put this to enum TestFramework.{JUnit|TestNG} so you would have List<TestFramework> above and in below for cycle you would have if (supportedTestAnnotations.contains(TestFramework.valueOf(annotation.getAnnotationType().getClassName())

File: jira/src/test/java/org/arquillian/extension/governor/jira/ITJiraGovernorTest.java [hunk 5]
```diff
@@ -25,6 +25,7 @@
 
 @RunWith(Arquillian.class)
 @RunAsClient
+@Jira("ARQ-831")
```
Comment (smiklosovic) [inline jira/src/test/java/org/arquillian/extension/governor/jira/ITJiraGovernorTest.java]: please add another test where jira will be placed in test method just as you deleted here in order to cover both cases

**Comment by smiklosovic** [comment]
I will merge it after my remarks. We can after this focus on a multiple jira servers, more or less implemented in my unfinished branch.

File: impl/src/main/java/org/arquillian/extension/governor/impl/ClosePassedDeciderImpl.java (hunk 2 above)
Comment (basovnik) [inline impl/src/main/java/org/arquillian/extension/governor/impl/ClosePassedDeciderImpl.java]: No. `@Jira` annotation has two properties `value` and `force`. Image situation that you set property `force` in `arquillian.xml` to `true` and then you have two `@Jira` annotations and only one of them contains property `force` set to true. It means that both of them will be always executed, but `equals` and `hashCode` methods will not evaluate those annotations to be the same. So `Map.get()` will not work. Therefore I compare annotations only according to its value. Both tests must succeed to close the issue. Therefore I use binary and `&` operator.

Example:
```java
@RunWith(Arquillian.class)
public class DummyTest
{
    @Test
    @Jira(value = "DUMMY-1")
    public void test1() {
        Assert.assertTrue(true);
    }

    @Test
    @Jira(value = "DUMMY-1", force="true")
    public void test2() {
        Assert.assertTrue(true);
    }
}
```
```xml
<arquillian>
    <extension qualifier="governor-jira">
        <property name="force">true</property>
    </extension>
</arquillian>
```

File: impl/src/main/java/org/arquillian/extension/governor/impl/GovernorTestClassScanner.java (hunk 3 above)
Comment (basovnik) [inline impl/src/main/java/org/arquillian/extension/governor/impl/GovernorTestClassScanner.java]: Yes, I do not know why I put there that condition. I will set it every time.

File: jira/src/test/java/org/arquillian/extension/governor/jira/ITJiraGovernorTest.java (hunk 5 above)
Comment (basovnik) [inline jira/src/test/java/org/arquillian/extension/governor/jira/ITJiraGovernorTest.java]: I am not sure if I understand you. Mentioned test class contains both types of `@Jira` annotation. As class level as method level annotation.

Comment (smiklosovic) [inline jira/src/test/java/org/arquillian/extension/governor/jira/ITJiraGovernorTest.java]: ah cool

File: impl/src/main/java/org/arquillian/extension/governor/impl/ClosePassedDeciderImpl.java (hunk 2 above)
Comment (smiklosovic) [inline impl/src/main/java/org/arquillian/extension/governor/impl/ClosePassedDeciderImpl.java]: ok

**Comment by smiklosovic** [comment]
good job
